name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # run "At 00:00 on Sunday"

# See https://github.com/cristalhq/.github/.github/workflows
jobs:
  build:
    uses: cristalhq/.github/.github/workflows/build.yml@711347e002043f2d3ed9293d83578b76d9bce0b3

  build-nodebug:
    uses: cristalhq/.github/.github/workflows/build.yml@711347e002043f2d3ed9293d83578b76d9bce0b3
    with:
      buildTags: nodebug
      groupSuffix: nodebug

  vuln:
    uses: cristalhq/.github/.github/workflows/vuln.yml@v0.8.0
