name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # run "At 00:00 on Sunday"

# See https://github.com/cristalhq/.github/.github/workflows
jobs:
  build:
    uses: cristalhq/.github/.github/workflows/build.yml@v0.7.0

  build:
    with:
      buildTags: nodebug
    uses: cristalhq/.github/.github/workflows/build.yml@cristaloleg-patch-1

  vuln:
    uses: cristalhq/.github/.github/workflows/vuln.yml@v0.7.0
